### ISSUE TITLE
Try to make taxon changes more efficient

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#3856] opened 2023-09-01 22:50 UTC
Someone recently swapped https://www.inaturalist.org/taxa/49150-Dione-vanillae with ~90k obs into a new taxon Agraulis vanillae (since reverted). The swap ran for 10 10 hour attempts and time out not having made it all the way through 
https://github.com/inaturalist/inaturalist/blob/main/app/models/taxon_change.rb#L217

This ticket is to look for ways to speed up large taxon changes like this

**Comment by pleary** [comment] 2024-05-09 16:58
Taxon changes should be much more efficient now after the changes in https://github.com/inaturalist/inaturalist/commit/577d84cdeeb203d4f7b734d85e1dfc7bc0a0e0aa. I don't know what the criteria are to close this ticket. Is there more to do for this? If so can we point to some reproducible conditions and a target so we can know when this has been sufficiently addressed?

**Comment by pleary** [comment] 2024-07-19 19:04
I'm going to close this as taxon changes were made more efficient since the ticket was created. If there are specific criteria not met, please reopen and detail the requirements needed to resolve this issue.

**Closed by pleary** 2024-07-19 19:04 UTC
Labels: bugs, rails
