### ISSUE TITLE
Getting into the admin brought up an error

### ISSUE THREAD

**Issue by chivoX** [inaturalist/inaturalist#1269] opened 2017-01-20 17:27 UTC
While triying to get into the admin i got this error

Running the command on the console:
Delayed::Backend::ActiveRecord::Job.possibly_active

NoMethodError: undefined method `possibly_active' for #<Class:0x007fe4748a88c8>

Seems like the models/delayed_job.rb file is not being loaded for some reason.

**Comment by pleary** [comment] 2017-01-20 18:01
Hi chivoX - I'm not sure what would cause that. I haven't seen that in any of our deployments. Again, I'm not sure the details of the environment you are running the code in, but please feel free to email me to talk it over. I'd email you but I don't see an email listed on your GitHub account.

So for now I'll close this because I cannot reproduce it. But if you email me we can talk more about your specific deployment of this codebase

**Closed by pleary** 2017-01-20 18:01 UTC
