### ISSUE TITLE
Unsubscribe link 

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#929] opened 2016-03-15 20:25 UTC
Currently for people to unsubscribe from iNat emails, they need to alter their account settings
<img width="470" alt="screen shot 2016-03-15 at 1 20 10 pm" src="https://cloud.githubusercontent.com/assets/598026/13792750/afa1216a-eab0-11e5-99bd-15678784d721.png">
which entails logging in and navigating the account UI
http://www.inaturalist.org/users/edit

The new email designs https://github.com/inaturalist/design/issues/51
include an 'unsubscribe' link

Ideally that link would lead to some route that would encode some sort of key that could be used to unsubscribe a user even if they aren't logged in.

For example this Foursquare link for me:
https://foursquare.com/email_unsubscribe?messageType=keep_in_the_know&ref=eo-blast_2016_mktg_wk11_FSLapsed_SFtastes-56e84364498e15cb94bf2d15&ts=1458072170362&userId=92933699&sig=zjWuxv%2FYFSru6Vt2%2FfDHfbkGJmc%3D
leads here
<img width="973" alt="screen shot 2016-03-15 at 1 23 13 pm" src="https://cloud.githubusercontent.com/assets/598026/13792838/1d53abce-eab1-11e5-9946-29e05ef9e58b.png">

I imagine that route would have a 'stop emailing me period' link and a 'alter my settings link'

@pleary thoughts on how to implement something like this?

**Comment by misdvickysue** [comment] 2016-03-23 03:46
Unsubscribe

**Comment by loarie** [comment] 2016-03-23 04:19
@misdvickysue ?

**Comment by kueda** [comment] 2018-06-01 21:40
#1797 is a duplicate of this, but I think it's more concise.

**Closed by kueda** 2018-06-01 21:40 UTC
Labels: improvements
