### ISSUE TITLE
Agreeing with an annotation you have added counts as another vote

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1775] opened 2018-05-14 19:38 UTC
From bouteloua:

See https://www.inaturalist.org/observations/12428139

![image](https://user-images.githubusercontent.com/15896181/40019301-b3de4280-5773-11e8-887c-1fea0f856541.png)

**Comment by kueda** [comment] 2018-05-16 00:08
That's how it was designed. Is it causing some kind of a problem?

**Comment by tiwane** [comment] 2018-05-16 00:36
From bouteloua: "There is one plant species that a user has gone through and annotated but they have mistaken the fruits for the buds in several cases and then agreed with their own annotations. Voting down to 'budding' does not fix the issue; the fruiting observations still show up in searches for budding plants of that species."

**Comment by kueda** [comment] 2018-05-16 00:40
The solution to that is to get more people to vote them down. We could disallow upvoting your own annotations, but that would mean you can't contest people contradicting you, e.g. you add an annotation of flowering, I vote it down, and then you can do nothing about it. Right now we have a one person one vote system, which seems mostly fair. @pleary designed this though, so maybe he has an opinion.

**Comment by tiwane** [comment] 2018-05-16 00:45
That makes sense.

**Comment by boucur** [comment] 2018-05-16 02:10
"but that would mean you can't contest people contradicting you, e.g. you add an annotation of flowering, I vote it down, and then you can do nothing about it"

Wouldn't the solution to that just be to get more people to vote it up? When you add the annotation, you have already voted up, it's just a hidden vote.

**Comment by kueda** [comment] 2018-05-16 04:04
I think the root of this issue is who to favor in situations without a majority, the person who added the annotation or the single dissenter, and I think that's somewhat arbitrary. You could argue (as we do for the community ID where we want *more* than a 2/3 majority, favoring a single dissenter against two other people) that someone who actually takes the time to vote *against* an annotation might have a higher probability of being right, because that's an extremely esoteric aspect of iNat that almost no one does aside from extremely active users who invest a lot of time into improving the system. On the other hand, you could argue that the person who added the annotation put in the work of adding the annotation in the first place, so if we have no reason to believe one vote over the other, why shouldn't we favor the person who did that initial work?

I don't think this is a pervasive problem, and I think the voting mechanism we have is sufficient to deal with the few problematic cases we have. The same thing happens with the captive / cultivated flag, in which some people try to pre-game it by always voting that things are wild, even when there's little reason to think they are, and I can't out-vote them and thus get mad, but it's a small minority of cases.

**Comment by boucur** [comment] 2018-05-16 13:07
The confusion with it not being prepopulated with a thumbs up after adding an annotation was one of the first things I mentioned on the GG when it was rolled out. I even have a bunch where I additionally thumbsupped because I didn't understand my vote was already counted. Extra time clicking with unintentional voting weight added. 

Right, obviously I agree with favoring the former situation (the person doing QC on annotations should be favored). Folks leave out budding and fruiting or annotate things as flowering when really budding pretty frequently--e.g. when the bracts are showy but flowers are not.

Really I just don't want to be the pedantic annoyance leaving comments on everyone's observations, most of whom are not the user who chose the wrong annotation. But I'll proceed... : )

**Comment by pleary** [comment] 2018-05-16 18:19
Voting on annotations was designed to work the same as voting on Data Quality (date is accurate, is wild, etc.) The way I see it, when an observation or annotation is created there is an assumption the creator believes it is valid and accurate. Without any votes we assume the date of the observation is accurate, or that they agree with the annotation. And in both cases the creator can take the extra step to vote yes/agree which adds weight in their favor, which leads to this case.

I like that voting works the same for Annotations and Data Quality, so I'd say if we change it for one we should change it for both. I'm not sure if this problem is more pervasive in Annotations vs Data Quality field. If it's becoming a problem, maybe there's some way we can guide or inform the user about how their vote is used. Like if there are no votes and they click yes/agree they see a popup asking "are you sure you want to double down on this?", similar to how we prompt for ID disagreements.

**Comment by kueda** [comment] 2018-05-22 22:26
Ok. I don't think this is broken and I don't think there's a clear problem to fix, so I'm closing.

**Closed by kueda** 2018-05-22 22:26 UTC
Labels: bugs

**Comment by boucur** [comment] 2018-08-24 13:17
For what it's worth, two other users thought this action (agreeing with an annotation you already added) was confusing/shouldn't be allowed: https://www.inaturalist.org/observations/15413912

**Comment by carrieseltzer** [comment] 2019-08-21 19:24
Just noting a user wrote to help@inat about the ability to vote on your own annotations as a possible bug.

**Comment by michaelpirrello** [comment] 2024-06-21 04:09
Although I think being able to agree with your own annotation is undesirable, I am in favor of leaving this feature as designed for a different reason. When you're plowing through a lot of annotations, occasionally you get an annotation that won't "stick" - my understanding is that the observation needs to be re-indexed? Being able to agree with another annotation is a quick way to do this, and often another of your annotations is the only one available for doing so.
