### ISSUE TITLE
Batch Edit - Editing large number of obs results in 504 Error, but edits usually go through

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2709] opened 2020-06-25 17:27 UTC
1. Set your Edit Observations page to show 50 results per page.
2. Click Batch Edit, select all, then Edit Selected.
3. Change the time zone for all observations and click Save at the bottom.
4. Get a 504 error.
5. Go to your Edit Observations page, refresh, and your batch edits have gone through.

**Comment by pleary** [comment] 2020-07-17 16:46
I didn't do much for this, but hopefully we'll see some improvements. All I did was change how we index observations for batch edits so we index all observations in bulk as opposed to one-by-one. In local testing this improved load time for a batch edit of 50 obs from 55 seconds to 9 seconds. I was able to get a batch to save on staging just now. If we see the same in production I'd be inclined to close this. There are probably other batch edits you could that will time out, but we can create a new ticket for that case when it comes up

**Comment by tiwane** [comment] 2020-07-18 02:40
Thanks Patrick

**Comment by pleary** [comment] 2020-07-20 15:11
it's taking about 15 seconds to save a batch of 50 right now. Not great, but it works. I'll close this ticket for now since I'm not getting an error and we can re-open if there's another reproducible case

**Closed by pleary** 2020-07-20 15:11 UTC
Labels: bugs
