### ISSUE TITLE
Collection project owner can't access location of observation

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3629] opened 2023-01-26 01:41 UTC
User efmer cannot access the true location of [this observation](https://www.inaturalist.org/observations/6537207 ), even though it is in their [BorregoWildflowers.org database project](https://www.inaturalist.org/projects/borregowildflowers-org-database) and the observer trusts them with all observations in the project.

**Comment by efmer** [comment] 2023-01-29 17:48
When you look into this the export file has the same problem, it doesn't show any of the obscured coordinates.

**Comment by jhorthos** [comment] 2023-01-29 17:55
I second this problem. When I try to obtain unobscured location data for project https://www.inaturalist.org/projects/serpentine-plants-of-the-western-united-states with Pingicula macroceras in California as a test case I get a file with header only and no data. There are 172 obscured observations (Research Grade) none of which are recovered.

- James
 (iNat jhorthos)

**Comment by jhorthos** [comment] 2023-01-29 18:19
Hmm my problem might be because (maybe) I am not allowed access yet. Apparently whenever I add a new taxon to the project list I get new wait period for access. (which is kind of pain in the neck - maybe that can be changed? it is already quite difficult to get folks signed on etc., doesn't seem to be much point in the wait period except perhaps when the project is first created).

**Comment by pleary** [comment] 2023-02-08 16:53
It seems like the problem here is that we are only allowing project owners to access these locations when the project attribute `observation_requirements_updated_at` exists and the value is at least [7 days ago](https://github.com/inaturalist/inaturalist/blob/main/app/models/project_user.rb#L39). In this case the value of `observation_requirements_updated_at` is nil. That attribute was added in [this commit](https://github.com/inaturalist/inaturalist/commit/5b346b11608c63811462cab60f378dcf6a8e0ea7) on 2021/01/28, and when I look at projects with user trust enabled where `observation_requirements_updated_at` is nil, they are all created before that commit was deployed.

My best guess for the root of this problem is when we deployed that change, we didn't retroactively set `observation_requirements_updated_at` to anything for projects that had already enabled user trust. It would have been set if their rules were ever changed, but if the rules were never changed the value would remain nil and owners wouldn't have been able to access private coords since a [corresponding API deploy](https://github.com/inaturalist/inaturalist/commit/5b346b11608c63811462cab60f378dcf6a8e0ea7) that checked that value.

If that seems right, then I'd recommend we now retroactively set `observation_requirements_updated_at` to at least 7 days ago for 255 affected projects, which should allow owners of those projects to access private coords of users in those projects that have opted-in.

**Comment by pleary** [comment] 2023-02-09 18:19
@kueda does that seem like a plausible cause for this bug? Can you see any problem with retroactively setting `observation_requirements_updated_at` to `ProjectUser::CURATOR_COORDINATE_ACCESS_WAIT_PERIOD.ago` for these 255 projects that have trust enabled, but where `observation_requirements_updated_at` is null (since they haven't updated requirements since the column was added)?

**Comment by kueda** [comment] 2023-02-09 18:52
...maybe. I addressed something similar in a2000abc8c67cceebcbd21638d285c91e0beee77, and according to my notes I also ran the following that *should* have fixed all the projects where trust was on but `observation_requirements_updated_at` was null:

```ruby
updated = []
Project.
    where( project_type: %w(collection umbrella) ).
    joins( :stored_preferences ).
    where( "preferences.name = 'user_trust' AND value = 't'" ).
    where( "observation_requirements_updated_at IS NULL" ).
    find_each do |proj|
  next if proj.collection_search_parameters.blank?
  proj.update_column( :observation_requirements_updated_at, proj.created_at )
  proj.elastic_index!
  puts "Updated #{proj}"
  updated << proj.id
end
```

It's entirely possible that I wrote that down with the intent to run it and never actually ran it, but if I did run it, then there's probably still some lingering way that a project can have trust enabled but `observation_requirements_updated_at` be null.

**Comment by pleary** [comment] 2023-02-09 20:35
It seems to me like that code never ran. There are still 230 collection and umbrella projects that query will find, and all of them created on or before 2021-01-29, when that column was added. I'm also not seeing any place the code would ever set `observation_requirements_updated_at` to null. If something were resetting `observation_requirements_updated_at` from some value to nil, I'd expect it to affect at least some newer projects as well.

Since you were planning on running this earlier, would you mind if I ran it now? I'll then confirm they all have values for that field and we can monitor if it ever gets turned back to nil

**Comment by kueda** [comment] 2023-02-13 18:26
Go ahead and run it, @pleary.

**Comment by efmer** [comment] 2023-02-13 23:12
I can see the observation mentioned in the first line and I can see another one.
So looks OK.
Should this resolve the export as well?

**Comment by pleary** [comment] 2023-02-13 23:23
Thanks for confirming. Yes this will hopefully fix the export as well. If you have the time, it would be worth testing that now too before I close the issue.

**Comment by pleary** [comment] 2023-02-14 18:21
I'll go ahead and close this access to the observation mentioned is resetored. @efmer if you try the export and find you can't access coordinates there, please feel comment here and feel free to reopen the issue. I can confirm that as of today, there are no projects that would be updated by @kueda's code above since all of them have values for `observation_requirements_updated_at`

**Closed by pleary** 2023-02-14 18:21 UTC
Labels: bugs
