### ISSUE TITLE
Header search highlights non-exact matches

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2516] opened 2019-12-12 22:22 UTC
From: https://forum.inaturalist.org/t/header-search-highlights-non-exact-matches/670

From @boucur: "Only text that exactly matches Petalostelma should be highlighted, but Petalostemon, Petalostigma are shown highlighted here. (This is the case for all header search queries, as well as for taxa, users, projects and places. This is just an example.)"

![image](https://user-images.githubusercontent.com/15896181/70753908-c1594700-1cea-11ea-83c6-31aa0e1818fd.png)

**Comment by kueda** [comment] 2019-12-12 23:43
Perhaps this is a misconception about what the highlights are: they are what terms the search engine matched given the query, not necessarily exact matches. Even more specifically they are the terms matched from the exact taxon names, autocomplete fields (which are generally matches against the beginning of the term only, e.g. "dog" would match "Dogmites" but not "Iconodog"), and descriptions (which I think might match any substring).

**Comment by boucur** [comment] 2019-12-12 23:55
Ah. Hm. It probably needs to be clearer when it's exactly matching vs. fuzzy matching then.

**Comment by kueda** [comment] 2020-01-24 00:40
Closing b/c this is working as intended.

**Closed by kueda** 2020-01-24 00:40 UTC
Labels: bugs
