### ISSUE TITLE
Can project filtering be improved in the Observation Search Page

### ISSUE THREAD

**Issue by shuetrim** [inaturalist/inaturalist#1169] opened 2016-10-06 21:11 UTC
**The issue**
It is unnecessarily hard for iNat users to grasp the implications of filtering by project in the [Observation Search Page (OSP)](http://www.inaturalist.org/observations).

**Proposed changes to OSP**
- Make it clearer to users which filters are being applied, without having to open the filter selection widget. e.g. Continue showing the place name when filtering by place. Add a project name/icon to the OSP if filtering by project. Add taxa names when filtering by taxonomic branches etc.

- Enable users to select, via the UI, more than one place filter and more than one taxonomic filter, where the taxon has been selected by name.

- When initially adding a project filter to the OSP, also add the filters implied by the project's observation eligibility rules. (perhaps, when the user is already on the page, give them the option of doing this or not doing it, when the have chosen a project filter).

**Motivation**
When viewing the OSP, the only way to find that you are filtering by project is to inspect the page URL or to tap the green badge to reveal the set of filters being used. That could be addressed by putting the project name/icon on the OSP when filtering by a project, in the same way that the place name is added to the OSP in place of "The World" when filtering by a place.

However, even if the use of the project filter was highlighted on the OSP, it is still not clear what filters are implicit in the project rules for observation eligibility. I would find it very helpful if those rules were also added explicitly by default when viewing the OSP with a project filter. They would need to be added in a way that could be changed by the user, as they refined their observation search (e.g. removing a place filter that was added on the basis of a project).

This suggestion has a number of issues that I can identify (and it may have others):

_Violations of observation eligibility rules_
- Observations in a project can violate the project's observation eligibility rules. For example, the rules could be added after the observations were added to the project. The observations might also be altered in ways that violate the rules, after having been added to the project (e.g. deleting photos or changing location or species ID). Filtering just by the project would enable the user to see these observations, but adding the filters implied by the project's observation eligibility rules would hide them. I would argue that given the project has chosen the observation eligibility rules, filtering by project should result in observations that match those rules. I would also argue that a determined user could find any violating observations by deleting the filters that were added by default when the user chose to filter by project. I would also argue that projects or at least their administrators should be able to find the set of violating observations more easily than through the OSP but I think that is a different issue.

_Redundancy_
- To the extent that observations do not violate the observation eligibility rules of a project, the filters based on those rules will be redundant. While true, the addition of those redundant rules, along with changes that make those rules more apparent when viewing the OSP, will ensure that users have a clearer understanding of how the observations they are seeing have been selected. The map will be centred and zoomed appropriately. The taxonomic and other restrictions will be right in front of them. They will also be in a position to make interesting filter changes (such as removing the project filter and leaving the redundant filters in place, so that they can, for example, quickly see if there are observations that would be eligible for inclusion in the project. 

_Place filters_
- The place restrictions in a project's observation eligibility rules might differ from the place that can optionally be associated with a project definition. In such cases, what should be done? Suggested answer: If the project has no place and it has no place rules, do not add a place filter to the OSP. If the project only has place rules, add a place filter for each rule. If a project has place rules and a place, only use the place rules to add place filters to the OSP.  Less confidently, I would suggest that if the project only has a place but no place rules, add that place as a filter (even though its semantics are unclear) because it is easier for a user to remove the place filter than to find the right place filter from among many similar ones.

- The OSP UI only appears to facilitate the use of a single place filter at one time. I think that limitation could be changed.

_Taxonomic filters_
- The OSP does not highlight which taxonomic filters are in effect unless the user examines the URL or opens the filter selection widget. Changing this would make it clearer to users how the observations that they are seeing have been chosen.

- Projects can filter based on membership of more than one taxonomic group: e.g. ray-finned fish and cartilaginous fish. I understand that the URL for the OSP facilitates support for more than one taxonomic filter but the user interface does not. I think that limitation could be changed.

_Other kinds of observation eligibility rules_
- I have not yet focused on other observation eligibility rules (e.g. license rules or photo rules) but I would try to handle them consistently, enabling them to all generate explicit filters that are added by default to the OSP when adding a project filter to the OSP. Where possible, I would also try to make it clear which of these filters are in effect without having to open the filter selection control.

**Resourcing the changes**
Suggestions like this one can skew existing work programs. If the group reaches  agreement on a set of changes based on this suggestion, lets then have a discussion about how the work might best be resourced.

**Comment by loarie** [comment] 2016-10-06 21:33
Hi Geoff

Looks like a few things going on here:

> 1. Make it clearer to users which filters are being applied, without having to open the filter selection widget.

The current system of using green badges was designed and user tested. So we wouldn't want to change things without objective data that an alternative would work better

> 2. e.g. Continue showing the place name when filtering by place.

the place filter does show the place. The location filter takes different data (e.g. addresses and is sent to Google to geo-reference. The location filter is not a place filter.

> 3. Add a project name/icon to the OSP if filtering by project.

It is currently displaying the project id or slug in the filters menu. Are you suggesting replace the id/slug with the icon and name?

> 4. Add taxa names when filtering by taxonomic branches etc.

The species filter does show the taxon name when a taxon filter is applied

> 5. Enable users to select, via the UI, more than one place filter and more than one taxonomic filter, where the taxon has been selected by name.

We've discussed building a UI for this. Would have to be designed though...

> 6. When initially adding a project filter to the OSP, also add the filters implied by the project's observation eligibility rules. (perhaps, when the user is already on the page, give them the option of doing this or not doing it, when the have chosen a project filter).

Why would you want to do this? If a project has must-be-in-place=1 and must-be-in-taxon=1 rules it is presumably already in effect filtering by taxon=1 and place=1 (since all project_observations would presumably be from taxon=1 and place=1). Why would you want to also redundantly filter on taxon=1 and place=1?

There's a bit too many topics in here for how we'd ideally like to keep Github issues. So I hope you don't mind if I close this, but numbers 3 and 5 seem to be precisely targeted that they might each warrant separate github issues if you'd like to make ones for them. 

As for the other numbers here, I've tried to express in my comments why its not clear that they represent bugs or objective improvements to existing designs.

Thanks for working through this process - apologies if any of this comes across as terse - just trying to get us as quickly as possible on the same page github-issue wise... really appreciate your interest and help developing the site

**Closed by loarie** 2016-10-06 21:33 UTC
