### ISSUE TITLE
Observations map missing markers or zoom/pan incomplete

### ISSUE THREAD

**Issue by synrg** [inaturalist/inaturalist#3636] opened 2023-01-28 09:08 UTC
[//]: # (For feature requests and bug reports not specifically concerning code, please use https://forum.inaturalist.org/c/feature-requests/16. iNat staff will make github issues if/when an actionable solution emerges)

**Describe the bug**
When displaying an observations map, it sometimes fails to set up completely. This is often noticed as the markers being completely absent from the map, but also can result in the zoom/pan not finishing, leaving the view window incorrectly positioned.

This has been noted and discussed before in these threads:

https://forum.inaturalist.org/t/how-to-refresh-map-to-show-observations/25339/17
https://forum.inaturalist.org/t/empty-explore-map/28400
https://forum.inaturalist.org/t/observations-map-doesnt-reliably-zoom-to-place-so-markers-can-be-seen/38393

I started a review of https://github.com/inaturalist/inaturalist/blob/main/app/assets/javascripts/ang/controllers/observation_search.js.erb and am suspicious of these 300ms and 500ms timeouts introduced in https://github.com/inaturalist/inaturalist/commit/053fed356d266ac83982661f3c8bf12106100d0e

```js
    // waiting a bit after creating the map to initialize the layers
    // to avoid issues with map aligning, letting the browser catch up
    setTimeout( function( ) {
      if( !$scope.mapLayersInitialized ) {
        $scope.setMapLayers( true );
        // more delays before enabling onMoves so setMapLayers
        // can finish aligning the map if it needs to
        setTimeout( function( ) {
          $scope.map.addListener( "dragstart", function( ) { $scope.delayedOnMove( ); });
          $scope.map.addListener( "center_changed", function( ) { $scope.delayedOnMove( ); });
          $scope.map.addListener( "zoom_changed", function( ) { $scope.delayedOnMove( ); });
        }, 500 );
      }
    }, 300);
```

Since then, that `setupMap()` function has grown to be a bit more complex, now including the setup of rectangular and circle map tools. I'm unsure whether or not that may exacerbate the problem.

I'm not even entirely sure it's either of these timeouts that causes the issue, but setting timers vs. responding to an event that is triggered upon completion of the map render seems dodgy at best. Perhaps the third-party map API provides some means to pass a callback when the whole map is finally set up and ready that could be used instead? Better yet, if it returned a promise we could await it ...

I didn't have time to set up a full test environment to investigate further, nor to dig into the Google maps API.

**To Reproduce**

1. Visit https://www.inaturalist.org/observations?place_id=97394&subview=map&taxon_id=427629
1. If it doesn't fail immediately, refresh the page until it fails to either show the markers, or to finish the zoom/pan

**Expected behavior**
The map should have markers for all observations, should be zoomed to the highest zoom level that still encompasses all of the observations, and should be panned to the center of all observations on the map.

**Screenshots**

These are from the report at <https://forum.inaturalist.org/t/empty-explore-map/28400>

No markers:

![image](https://user-images.githubusercontent.com/1204376/215256989-8da69fd1-8a03-4884-b90d-cfa4f636f65a.png)

Pan incomplete:
![image](https://user-images.githubusercontent.com/1204376/215257017-21d671e2-b54f-4edb-a6ad-33887f085918.png)
![image](https://user-images.githubusercontent.com/1204376/215257026-1680bb7c-3a0f-47c0-a9a4-7c2aae57b8c1.png)
![image](https://user-images.githubusercontent.com/1204376/215257035-00b2493e-7180-4fdd-bace-e2cbf8cba948.png)

**Context**
 - OS: Windows or Linux
 - Browser Chrome or Firefox
 - Version Chrome 109, Firefox 109

**Comment by kueda** [comment] 2023-01-30 19:40
FWIW, I cannot replicate this on my Mac, but @sylvain-morin can replicate in Ubuntu 22.04, Chrome 108.0.5359.124. It's seems unlikely to me that this is really related to the OS, but maybe variable network performance? @benkeen, any thoughts on this?

**Comment by benkeen** [comment] 2023-01-31 06:33
Nothing of any great help, I'm afraid @kueda.

"Dodgy at best" is a pretty good descriptor of the timeouts, I quite agree @synrg.  I haven't seen the problem myself either (Chrome, Mac) during quite a bit of development on the drawing tools, but it sure looks like a timing issue to me as well. With such complex logic as that map code, a single request taking a little longer than others could throw off the rendering logic and cause all sort of oddities. Especially when you throw in hardcoded timeout times. The new drawing tools could certainly have contributed to the problem, it's hard to say.

**Comment by synrg** [comment] 2023-01-31 09:07
Makes sense that network throttling would affect it. I tried again this morning, and simply disabling cache and reloading the page 100% reproduces the "empty map" symptom for me, i.e. with cache disabled, page reload *never* displays markers or performs zoom/pan. With cache re-enabled and throttling at "DSL" (Firefox), only one out of several times reproduced the pan bug, and the rest (apart from the initial page load to refill the cache that was empty) were normal.

**Comment by rainhead** [comment] 2023-02-17 00:19
Just peeking at this issue. I notice that our Google Maps integration is out out of date:
```
Loading the Google Maps JavaScript API without a callback is not supported: https://developers.google.com/maps/documentation/javascript/url-params#required_parameters
Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
```

There is perhaps a short-term fix for our issue, but it also looks like it's time to upgrade. I looked briefly and didn't see an existing issue to do so.

**Comment by rainhead** [comment] 2023-02-17 00:26
Also: if I disable cache and throttle to "regular 3G", the map remains empty. This is Firefox 109.0.1 on an M1 MacBook Air. A `GET` request for `https://api.inaturalist.org/v1/observations/148477555?locale=en-US&preferred_place_id=1` does not complete. I'm actually not sure what state it's in, it's not clear to me from the Developer Tools window.

**Comment by rainhead** [comment] 2023-04-04 17:44
I looked into improving the loading of maps. We have maps on quite a few different pages, with some significant variation in how they are initialized. In the more complicated cases, initialization involves interaction between the DOM, script tags, views and layouts, and different JS files or modules, some of them preprocessed by ERb. The JS is a mix of Google's libraries, jQuery, Angular, vendored open source scripts with customizations and bug fixes, and our own glue code, each of which has implicit assumptions about what information has been made available through the DOM or global variables, what kinds of initialization have already taken place, and how long other pieces of code take to do their thing. There are no tests or specifications, so it would be hard to know if even a small change broke anything.

Fixing this means creating a new architecture and porting over (and documenting) behavior piece by piece, map by map, starting with the most straight-forward maps. We would need to agree on key elements of the new architecture.

**Comment by synrg** [comment] 2023-04-05 07:27
Given all of that will take a while, and assuming that we're in a period of suffering this issue more than we did before the introduction of the new selection tools, can we at least patch over whatever increases in latencies there now are due to that additional complexity with longer timeout values until it can be fixed properly?

**Comment by rainhead** [comment] 2023-04-07 00:49
All of that will take a good while, if we agree to do it.

Do we have a measure of the severity of the suffering? How often is this happening?

**Comment by synrg** [comment] 2023-04-07 08:39
At least for some people, frequently enough to be annoying, e.g.

In https://forum.inaturalist.org/t/observations-map-doesnt-reliably-zoom-to-place-so-markers-can-be-seen/38393/2 `@Marina_Gorbunova` says:
> Can confirm it happens pretty often with boundaries search.

In https://forum.inaturalist.org/t/observations-map-doesnt-reliably-zoom-to-place-so-markers-can-be-seen/38393/5 `@earthknight` says:
> I’ve been having this happen more and more often recently, and not even with a search that’s limited by boundaries.

It's a small sample size, but because they indicate frequent incidence, and also that it seems to have worsened recently, it could be affecting more people lately, more often, ever since the introduction of the new selection tools (we think).

**Comment by rainhead** [comment] 2023-04-19 02:03
Also https://forum.inaturalist.org/t/i-cant-reach-maps-and-some-pages/41001

**Comment by rainhead** [comment] 2023-07-03 19:02
@kueda I see this is assigned to me. What level of investment do you want? The cheapest option is presumably to lengthen some timeouts, making everything slower to initialize even on fast systems / small maps. The most expensive option is to establish a new interface for configuring maps and to progressively roll that out starting with the simplest / smallest use cases on the site. There may or may not be reasonable options in between.

**Comment by pleary** [comment] 2023-08-31 23:08
I believe this has been resolved, so I'll close this. But if anyone can come up with steps to reproduce, please re-open with examples. Explore/Observations Search is now using the asynchronous method of loading Google Maps, and only running custom JS on the search page after maps is available. Various changes have been made including removing timeouts, lots of code formatting cleanup, and general rearranging order of processes to help things work better. This code is still a bit of a mess though, so looking forward to the day we have time to re-write this in React to better reuse existing components and end up with cleaner code that's easier to follow, debug, and maintain.

Thanks to everyone that put time into this.

**Closed by pleary** 2023-08-31 23:08 UTC
Labels: bugs, javascript
