### ISSUE TITLE
clicking agree quickly on identify produces 2 current IDs

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1593] opened 2018-01-05 02:49 UTC
e.g. from here https://www.inaturalist.org/observations/identify?quality_grade=research&user_id=johncomstock clicking on the modal agree 2 times quick
<img width="1183" alt="screen shot 2018-01-04 at 6 48 16 pm" src="https://user-images.githubusercontent.com/598026/34593468-e98fb012-f17f-11e7-8925-d98145bee8ec.png">

produces
<img width="1166" alt="screen shot 2018-01-04 at 6 48 26 pm" src="https://user-images.githubusercontent.com/598026/34593470-ec8a6cbc-f17f-11e7-897f-b8bc045ccad4.png">

**Comment by kueda** [comment] 2018-01-06 18:41
I'm pretty sure this is a duplicate of #1491

**Closed by kueda** 2018-01-06 18:41 UTC
Labels: bugs
