### ISSUE TITLE
Suppress re-notification about journal posts after edits

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1090] opened 2016-08-02 18:06 UTC
Last week I edited a journal post about the Great Nature Project not knowing that it would put the 6 month old post back in everyone's dashboard (and email). I suppose that was ok for people who missed the announcement in January, but I'd like to be able to edit old journal posts without them being blasted out again (e.g. to fix broken links). 

File this under low priority improvements, and until then I won't edit any more old journal posts!

**Comment by kueda** [comment] 2016-08-02 18:35
I actually thought I fixed that recently. Did you edit a published post, save it as a draft, and then publish it again?

**Comment by pleary** [comment] 2016-08-02 18:37
This is almost certainly related to the updates changes released on Thursday. I'd be interested to know the steps to reproduce this. I purposely stripped out logic and queries to make updates faster, and was expecting problems like this. Once I know how to reproduce them I can update the code to prevent them (as efficiently as possible)

**Comment by carrieseltzer** [comment] 2016-08-02 18:57
Hmm. It's possible that I re-saved it as a draft. Let me try with a project with a much smaller audience first.

**Comment by carrieseltzer** [comment] 2016-08-02 19:12
Weird. I can't replicate this. I joined a small project I admin using a different account, then using my main user account with project admin status I tried all of these things, none of which triggered a dashboard update like what happened last week with GNP:

1. Made a small edit (added hyphen) and saved. 
2. Added a line of text and saved. 
3. Added more to that line, hit preview first, then saved.
4. Added a hyperlink, previewed, then saved.
5. Deleted the new line with hyperlink, previewed, and saved.

I'm out of ideas. Any chance that what you changed on Thursday happened after my post and not before? Maybe @kueda's fix hadn't been released yet? For timing, my post shows: "updated_at_utc": "2016-07-25T20:14:20.107Z"

**Comment by pleary** [comment] 2016-08-02 19:39
OK I see now this all happened on 7/25 before the `updates` modifications on Thursday 7/28, so this would have happened with the older code. It is possible the problem is fixed in the newer code. I'll test out this scenario on some test data and see if I can replicate it

**Comment by kueda** [comment] 2016-08-04 18:00
I can't replicate this. In theory a post should not generate an update unless it is just changed to be published. So if you unpublished and republished, that should generate new updates, but just doing the editing you described should not.

If you can replicate this, please re-open this issue.

**Closed** 2016-08-04 18:25 UTC
Labels: bugs
