### ISSUE TITLE
Adding taxon with a new source fails

### ISSUE THREAD

**Issue by mikkohei13** [inaturalist/inaturalist#2992] opened 2021-04-01 06:24 UTC
**Describe the bug**

Submitting https://www.inaturalist.org/taxa/new will fail if new source is filled in.

**To Reproduce**

1. Go to https://www.inaturalist.org/taxa/new
1. Fill in scientific name, rank, and parent id (using the lookup)
1. Under Source, click add new source
1. Fill in title, in text, url and citation
2. Click Save changes

**Expected behavior**

Adding the taxon succeeds

**Actual behavior**

Error message "I ate iNaturalist.org, that's why it's not working."

**Context**

 - OS: Windows 10
 - Browser Chrome
 - Version 89

**Additional context**

Problem existed already 2-3 weeks ago, and again today. If new literature source is not filled in, there's no error.

**Comment by kueda** [comment] 2021-04-02 01:12
I was not able to replicate the crash with the steps provided. Can you describe the values you're filling in at each step and/or provide screenshots?

**Comment by kueda** [comment] 2021-04-14 16:59
@mikkohei13 I'm going to close this since I couldn't replicate it following the steps you provided. If you can provide steps I can follow to consistently reproduce this problem, please re-open and/or leave a comment.

**Comment by mikkohei13** [comment] 2021-04-15 15:02
Sorry for the delay, here's the info that fails:

![image](https://user-images.githubusercontent.com/403243/114891621-b5b4ed80-9e14-11eb-9fbf-824f310cd137.png)

**Closed** 2021-04-15 19:14 UTC
Labels: bugs
