### ISSUE TITLE
Observation count in user profile cached but not directly invalidated when updated

### ISSUE THREAD

**Issue by davidak** [inaturalist/inaturalist#3904] opened 2023-10-16 16:58 UTC
**Describe the bug**

The observation count in the user profile is cached and not directly updated when new observations are added.

**To Reproduce**
1. Go to your profile page
1. Check observation count
1. Add observations (in my case it was 2)
1. Check observation count again

**Expected behavior**
The observation count in the profile should be updated with the new observations.

**Screenshots**
![Screenshot from 2023-10-16 18-41-06](https://github.com/inaturalist/inaturalist/assets/91113/db0e02ac-6045-4669-a933-29afe759ce1e)

**Context**
 - OS: NixOS 22.11.4588.93fddcf640c
 - Browser: Google Chrome 114.0.5735.133

**Additional context**
I had 658 observations, added 2, then it was 659.
The page with my own observations had the correct value.

After 10 minutes, it was still not updated to the correct value.

After 17 minutes it was. Maybe the cache TTL is 15 minutes?

The cache should be invalidated when the number of observations (or any other number displayed) changes. Or don't cache at all. A database can also cache.

Related: https://github.com/inaturalist/inaturalist/issues/2835

cc @kueda

**Comment by kueda** [comment] 2023-10-16 17:53
Duplicate of #1114, but this definitely has a lot of good additional context, so thanks for that, @davidak.

**Closed by kueda** 2023-10-16 17:53 UTC
