### ISSUE TITLE
bug where iNat tries to graft taxa from external sources to the wrong branches

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1764] opened 2018-05-09 04:47 UTC
I've noticed this over the years but never really investigated. Was brought up again here: https://www.inaturalist.org/flags/232667#comment-1754921
worth looking into

**Comment by kueda** [comment] 2018-05-11 20:03
Pretty sure this is a duplicate of #1602

**Closed by kueda** 2018-05-11 20:03 UTC
Labels: bugs
