### ISSUE TITLE
URL doesn't preserve map coords/markers for place_id

### ISSUE THREAD

**Issue by portedison** [inaturalist/inaturalist#3810] opened 2023-07-13 04:19 UTC
**Describe the bug**
When loading a page, with a place_id (and taxon_id) in the url, it does't preserve the maps coords, bounds or markers.
NOTE. observations are as expected, just not rendering on the map.

_Potentially related, console message.
Loading the Google Maps JavaScript API without a callback is not supported: https://developers.google.com/maps/documentation/javascript/url-params#required_parameters_

**To Reproduce**
Bug.
1. Visit https://www.inaturalist.org/observations?place_id=40469&subview=map&taxon_id=131669

Expected view.
1. Visit https://www.inaturalist.org/observations
2. Search Species : Cyathea dealbata, Location : Christchurch, New Zealand

**Comment by jwidness** [comment] 2023-07-13 04:39
Duplicate of #3636

**Comment by pleary** [comment] 2023-07-13 14:17
I'll close this as I agree this is a duplicate of #3636

**Closed** 2023-07-13 16:31 UTC
